---
title: "Demo"
author: "Dhaneswara Mandrasa T."
date: "12/20/2019"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(dplyr, tidyr, stringr, stringi, purrr,
               tibble, rvest, polite, lubridate,
               ggplot2, jsonlite, xml2, qdapRegex,
               ggtext, extrafont, ggrepel, ggforce,
               understatr, ggsoccer,
               grid, gridExtra)
library(englelab)
loadfonts(quiet = TRUE)
```


## understat utility funs

```{r}
get_script <- function(x) {
  as.character(html_nodes(x, "script"))
}
# subset data element of html page
get_data_element <- function(x, element_name) {
  stri_unescape_unicode(str_subset(x, element_name))
}
# fix json element for parsing
fix_json <- function(x) {
  str_subset(
    unlist(
      rm_square(
        x, extract = TRUE, include.markers = TRUE
      )
    ),
    "\\[\\]", negate = TRUE
  )
}
# get player name part of html page
get_player_name <- function(x) {
  player_name <- html_nodes(x, ".header-wrapper:first-child")
  trimws(html_text(player_name))
}
```


```{r, fig.height=8, fig.width=10}
pitch_custom <- list(
  length = 1084,
  width = 878,
  penalty_box_length = 224,
  penalty_box_width = 493,
  six_yard_box_length = 73,
  six_yard_box_width = 247,
  penalty_spot_distance = 150,
  goal_width = 99,
  origin_x = 0,
  origin_y = 0
)


df <- data.frame(x = 1042.604, y = 534.604)

ggplot(df) +
  annotate_pitch(dimensions = pitch_custom) +
  theme_pitch(aspect_ratio = 878/1084) +
  coord_flip(xlim = c(550, 1085),
              ylim = c(-1, 880)) +
  geom_point(aes(x = x, y = y), shape = 21,
             fill = "red",
             colour = "red", size = 5) +
  geom_point(x = 1080, y = 850)

ggplot(df) +
  annotate_pitch(dimensions = pitch_custom) +
  theme_pitch(aspect_ratio = 878/1284) +
  geom_point(x = 0, y = 0) +
  geom_point(x = 600, y = 878)
```

# Pitch Custom For FPL

## Option 1
```{r}
pitch_custom <- list(
  length = 1084,
  width = 878,
  penalty_box_length = 224,
  penalty_box_width = 493,
  six_yard_box_length = 73,
  six_yard_box_width = 247,
  penalty_spot_distance = 150,
  goal_width = 99,
  origin_x = 0,
  origin_y = 0
)

df <- data.frame(x = 1060, y = 360)

ggplot(df) +
  annotate_pitch(colour = "white",
                 fill   = "chartreuse4",dimensions = pitch_custom) +
  theme_pitch(aspect_ratio = 700/1400) +
  coord_flip(xlim = c(700, 1085),
              ylim = c(0, 900)) +
  geom_point(aes(x = x, y = y), shape = 21,
             fill = "red",
             colour = "red", size = 5) 
```

## Option 2
```{r}
shots <- data.frame(x = c(96.3, 84.9),
                    y = c(57.9, 59))
ggplot(shots) +
  annotate_pitch(colour = "white",
                 fill   = "black",
                 limits = FALSE) +
  geom_point(aes(x = x + 2, y = 98 - y),
             colour = "yellow", 
             size = 4) +
  theme_pitch(aspect_ratio = 700/1200) +
  theme(plot.background = element_rect(fill = "black"),
        title = element_text(colour = "white")) +
  coord_flip(xlim = c(49, 101),
             ylim = c(-1, 101))

```

## Salah
```{r}
  circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
      r = diameter / 2
      tt <- seq(0,2*pi,length.out = npoints)
      xx <- center[1] + r * cos(tt)
      yy <- center[2] + r * sin(tt)
      return(data.frame(x = xx, y = yy))
  }


salah <- understatr::get_player_shots(1250) %>% mutate(result = as.factor(result))

library(plotly)
salah
ggplotly(ggplot(data) +
  annotate_pitch(colour = "white",
                 fill   = "black",
                 limits = F) +
  geom_point(aes(x = (X*100) + 2, y = 98 - (Y*100), col = result, size = xG)) +
  theme_pitch(aspect_ratio = 700/1200) +
  theme(plot.background = element_rect(fill = "black"),
        title = element_text(colour = "white"), legend.position = "none") +
  coord_flip(xlim = c(49, 101),
             ylim = c(-1, 101))) %>% 
layout(plot_bgcolor='black') %>% 
layout(paper_bgcolor='black') 

annota
```


# Match Summary Stats

```{r}
match_url <- stringr::str_glue("{home_url}/match/{match_id}")
match_page <- polite::bow(match_url)
team_stats <- polite::scrape(match_page) %>% 
  html_nodes("div.scheme-block:nth-child(4)") %>% 
  html_text() %>% 
  str_remove_all(., "CHANCES") %>% 
  str_remove_all(., "([0-9]{2,}%)") %>% 
  str_replace_all(., "SHOTS ON TARGET", "ON-TARGET") %>% #trimws() %>% 
  str_squish() %>% 
  read.table(text = ., header = FALSE, sep = " ",
             col.names = c("var_name", "home", "away")) %>% 
  t() %>% 
  tibble::as_tibble() %>% 
  janitor::row_to_names(row_number = 1) %>% 
  mutate_at(vars(-TEAMS), ~ as.numeric(.))
home_stats <- team_stats[1,]
away_stats <- team_stats[2,]
team_stats
```
# Liv-Nor


```{r}
home_url <- "https://understat.com"
match_id <- 11643
```

```{r}
match_url <- stringr::str_glue("{home_url}/match/{match_id}")
match_page <- polite::bow(match_url)
match_data <- polite::scrape(match_page) %>% 
  get_script()
match_shots_data <- get_data_element(match_data, "shotsData")
#msd <- jsonlite::stream_in(match_shots_data)
match_shots_data <- fix_json(match_shots_data)
# Home: Liverpool
liv_shots_data <- fromJSON(match_shots_data[1])
## add 'team_name' with home team name from 'h_team' var
liv_shots_data$team_name <- liv_shots_data$h_team
# Away: Arsenal
nor_shots_data <- fromJSON(match_shots_data[2])
## add 'team_name' with away team name from 'a_team' var
nor_shots_data$team_name <- nor_shots_data$a_team
```


```{r}
match_shots_data_clean <- liv_shots_data %>% 
  full_join(nor_shots_data) %>% 
  select(-id, -h_team, -a_team,
         -h_goals, -a_goals) %>% 
  mutate_at(vars(minute, xG, X, Y, 
                 player_id, match_id, season), ~ as.numeric(.)) %>% 
  mutate(team_name = forcats::as_factor(team_name),
         xG = if_else(is.na(xG), 0, xG) %>% round(digits = 2),
         result = case_when(
           result == "SavedShot" ~ "Saved Shot",
           result == "BlockedShot" ~ "Blocked Shot",
           result == "MissedShots" ~ "Missed Shot",
           result == "ShotOnPost" ~ "On Post",
           result == "OwnGoal" ~ "Own Goal",
           TRUE ~ result),
         situation = case_when(
           situation == "OpenPlay" ~ "Open Play", 
           situation == "FromCorner" ~ "From Corner",
           situation == "DirectFreekick" ~ "From Free Kick",
           TRUE ~ situation),
         lastAction = case_when(
           lastAction == "BallRecovery" ~ "Ball Recovery",
           lastAction == "BallTouch" ~ "Ball Touch",
           lastAction == "LayOff" ~ "Lay Off",
           lastAction == "TakeOn" ~ "Take On",
           TRUE ~ lastAction),
         shotType = case_when(
           shotType == "LeftFoot" ~ "Left Foot",
           shotType == "RightFoot" ~ "Right Foot",
           TRUE ~ shotType)) %>% 
  separate(player, into = c("firstname", "player"), 
           sep = "\\s", extra = "merge") %>% 
  ## players like Fabinho listed without Tavares last name
  mutate(player = if_else(is.na(player), firstname, player))
last_min <- match_shots_data_clean$minute %>% unique() %>% last()
minute <- c(0:last_min)
team_name <- c("Liverpool", "Norwich")
livnor_rollsumxG <- match_shots_data_clean %>% 
  full_join(crossing(minute, team_name)) %>% 
  arrange(minute) %>% 
  group_by(team_name) %>% 
  mutate(xG = if_else(is.na(xG), 0, xG) %>% round(digits = 2),
         rollsum = lag(cumsum(xG))) %>% 
  ungroup() %>% 
  mutate(player_label = case_when(
    result == "Goal" ~ glue::glue("{player}: {xG %>% round(digits = 2)} xG"),
    result == "Own Goal" ~ glue::glue("{player} (Own Goal): {xG %>% round(digits = 2)} xG"),
    TRUE ~ ""),
    ## 
    rollsum_goal = rollsum + xG,
    minute_goal = minute + 1)
```


## accumulated xG plot

```{r, fig.height=6, fig.width=10}
cumsum_xG_plot <- livnor_rollsumxG %>% 
  ggplot(aes(x = minute_goal, y = rollsum_goal, 
             color = team_name, group = team_name)) +
  geom_line(size = 2.5) +
  geom_label_repel(data = livnor_rollsumxG %>% 
                     filter(result %in% c("Goal", "Own Goal")),
                   aes(x = minute_goal, y = rollsum_goal, 
                       color = team_name, label = player_label),
                   nudge_x = -10, nudge_y = 0.35,
                   show.legend = FALSE) +
  geom_point(data = livnor_rollsumxG %>% 
               filter(result %in% c("Goal", "Own Goal")),
             aes(x = minute_goal, y = rollsum_goal, 
                       color = team_name),
             size = 5, shape = 21, fill = "white", stroke = 1.25,
             show.legend = FALSE) +
  scale_x_continuous(breaks = c(seq(0, 90, by = 5), 91),
                     labels = c(seq(0, 40, by = 5), "HT", 
                                seq(50, 85, by = 5),"", "FT"),
                     expand = c(0.01, 0),
                     limits = c(0, 91)) +
  scale_y_continuous(limits = c(0, 3),
                     sec.axis = sec_axis(~ ., breaks = team_stats$xG)) +
  scale_color_manual(
    values = c("Liverpool" = "#d00027",
               "Norwich" = "#00a650"),
    breaks = c("Liverpool", "Norwich"),
    labels = c("<b style ='color:#d00027'>Liverpool</b>",
               "<b style='color: #00a650'>Norwich</b>")) +
  labs(title = glue::glue("<b style ='color:#d00027'>{home_stats$TEAMS}: {home_stats$GOALS} </b><b style ='color:#d00027; font-size: 20'>({home_stats$xPTS} xPTs)</b><br> <b style='color: #00a650'>{away_stats$TEAMS}: {away_stats$GOALS} </b><b style='color: #00a650; font-size: 20'>({away_stats$xPTS} xPTs)</b>"),
       subtitle = "August 9, 2019 (Matchday 1)",
       x = NULL,
       y = "Expected Goals") +
  theme_minimal() 
cumsum_xG_plot
```

# xG Pitch Plot

not perfect but eh, serviceable!

```{r, fig.height=8, fig.width=10}
pitch_custom <- list(
  length = 587,
  width = 373,
  penalty_box_length = 101,
  penalty_box_width = 211,
  six_yard_box_length = 31,
  six_yard_box_width = 111,
  penalty_spot_distance = 66,
  goal_width = 45,
  origin_x = 0,
  origin_y = 0
)
```

```{r, fig.height=8, fig.width=10}
df <- data.frame(x = 570, y = 190)
ggplot(df) +
  annotate_pitch(dimensions = pitch_custom) +
  theme_pitch(aspect_ratio = 373/587) +
  geom_point(aes(x = x, y = y), 
             colour = "red", size = 2) +
  geom_point(x = 0, y = 0, 
             colour = "red", size = 2) +
  geom_point(x = 0, y = 219, 
             colour = "red", size = 2) +
  geom_point(x = 524, y = 186.5, 
             colour = "blue", size = 2) 
```

```{r}
pitch_custom2 <- list(
  length = 100,
  width = 100,
  penalty_box_length = 17,
  penalty_box_width = 58,
  six_yard_box_length = 6,
  six_yard_box_width = 26.4,
  penalty_spot_distance = 11,
  goal_width = 7.3,
  origin_x = 0,
  origin_y = 0
)
```

```{r, fig.height=8, fig.width=10}
liv_shots_data %>% 
  mutate_at(vars(X, Y, xG), ~ as.numeric(.)) %>% 
  mutate(x = X * 100,
         y = Y * 100) %>% 
  select(minute, player, result, X, x, Y, y, xG) %>% 
  ggplot() +
  annotate_pitch(dimensions = pitch_custom2) +
  theme_pitch(aspect_ratio = 800/1000) + 
  geom_point(aes(x = x, y = y, size = xG), 
             colour = "red", show.legend = FALSE)
```



