---
title: "pitch"
author: "Dhaneswara Mandrasa T."
date: "12/20/2019"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(dplyr, tidyr, stringr, stringi, purrr,
               tibble, rvest, polite, lubridate,
               ggplot2, jsonlite, xml2, qdapRegex,
               extrafont, ggrepel, ggforce,
               understatr, ggsoccer,
               grid, gridExtra)
library(englelab)
library(ggplot2)
library(plotly)
loadfonts(quiet = TRUE)
```

# Pitch Custom For FPL

## Option 1
```{r}
pitch_custom <- list(
  length = 1084,
  width = 878,
  penalty_box_length = 224,
  penalty_box_width = 493,
  six_yard_box_length = 73,
  six_yard_box_width = 247,
  penalty_spot_distance = 150,
  goal_width = 99,
  origin_x = 0,
  origin_y = 0
)

df <- data.frame(x = 1060, y = 360)

ggplot(df) +
  annotate_pitch(colour = "white",
                 fill   = "chartreuse4",dimensions = pitch_custom) +
  theme_pitch(aspect_ratio = 700/1400) +
  coord_flip(xlim = c(700, 1085),
              ylim = c(0, 900)) +
  geom_point(aes(x = x, y = y), shape = 21,
             fill = "red",
             colour = "red", size = 5) 


```

## Option 2
```{r}
shots <- data.frame(x = c(96.3, 84.9),
                    y = c(57.9, 59))
ggplot(shots) +
  annotate_pitch(colour = "white",
                 fill   = "black",
                 limits = FALSE) +
  geom_point(aes(x = x + 2, y = 98 - y),
             colour = "yellow", 
             size = 4) +
  theme_pitch(aspect_ratio = 700/1200) +
  theme(plot.background = element_rect(fill = "black"),
        title = element_text(colour = "white")) +
  coord_flip(xlim = c(49, 101),
             ylim = c(-1, 101))

```

```{r}

library(plotly)

ggplotly(ggplot(salah %>% dplyr::filter(date >= "2018-08-01" & date <= "2019-05-31")) +
  annotate_pitch(colour = "white",
                 fill   = "black",
                 limits = F) +
  geom_point(aes(x = (X*100) + 2, y = 98 - (Y*100), col = result, size = xG)) +
  theme_pitch(aspect_ratio = 700/1200) +
  theme(plot.background = element_rect(fill = "black"),
        title = element_text(colour = "white"), legend.position = "none") +
  coord_flip(xlim = c(49, 101),
             ylim = c(-1, 101))) %>% 
layout(plot_bgcolor='black') %>% 
layout(paper_bgcolor='black') 

```


# Function 
```{r}
createPitch <- function(xmax, ymax, grass_colour, line_colour, background_colour, goal_colour) {
  theme_blankPitch = function(size=12) { 
    theme(
      #axis.line=element_blank(), 
      axis.text.x=element_blank(), 
      axis.text.y=element_blank(), 
      #axis.ticks.y=element_text(size=size),
      #   axis.ticks=element_blank(),
      axis.ticks.length=unit(0, "lines"), 
      #axis.ticks.margin=unit(0, "lines"), 
      axis.title.x=element_blank(), 
      axis.title.y=element_blank(), 
      legend.background=element_rect(fill=background_colour, colour=NA), 
      legend.key=element_rect(colour=background_colour,fill=background_colour), 
      legend.key.size=unit(1.2, "lines"), 
      legend.text=element_text(size=size), 
      legend.title=element_text(size=size, face="bold",hjust=0),
      strip.background = element_rect(colour = background_colour, fill = background_colour, size = .5),
      panel.background=element_rect(fill=background_colour,colour=background_colour), 
      #       panel.border=element_blank(), 
      panel.grid.major=element_blank(), 
      panel.grid.minor=element_blank(), 
      panel.spacing=element_blank(), 
      plot.background=element_blank(), 
      plot.margin=unit(c(0, 0, 0, 0), "lines"), 
      plot.title=element_text(size=size*1.2), 
      strip.text.y=element_text(colour=background_colour,size=size,angle=270),
      strip.text.x=element_text(size=size*1))}
  
  ymin <- 0 
  xmin <- 0 
  
  # Defining dimensions
  GoalWidth <- 732*1.25
  penspot <- 1100*1.25
  boxedgeW <- 4032
  boxedgeL <- 1650*1.25
  box6yardW <- 1832*1.25
  box6yardL <- 550*1.25
  
  ## dimensions calculations 
  # The 18 Yard Box
  TheBoxWidth <- c(((ymax / 2) + (boxedgeW / 2)),((ymax / 2) - (boxedgeW / 2)))
  TheBoxHeight <- c(boxedgeL,xmax-boxedgeL)
  GoalPosts <- c(((ymax / 2) + (GoalWidth / 2)),((ymax / 2) - (GoalWidth / 2)))
    
  # The 6 Yard Box
  box6yardWidth <- c(((ymax / 2) + (box6yardW / 2)),((ymax / 2) - (box6yardW / 2)))
  box6yardHeight <- c(box6yardL,xmax-box6yardL)
  
  ## Centre circle dimensions 
  centreCirle_d <- 1830
  
  ## define the circle function
  circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
      r = diameter / 2
      tt <- seq(0,2*pi,length.out = npoints)
      xx <- center[1] + r * cos(tt)
      yy <- center[2] + r * sin(tt)
      return(data.frame(x = xx, y = yy))
  }
  
  #### create leftD arc ####
  Dleft <- circleFun(c((penspot),(ymax/2)),centreCirle_d,npoints = 1000)
  ## remove part that is in the box
  Dleft <- Dleft[which(Dleft$x >= (boxedgeL)),]
  
  ## create rightD arc  ####
  Dright <- circleFun(c((xmax-(penspot)),(ymax/2)),centreCirle_d,npoints = 1000)
  ## remove part that is in the box
  Dright <- Dright[which(Dright$x <= (xmax-(boxedgeL))),]
  
  #### create center circle ####
  center_circle <- circleFun(c((xmax/2),(ymax/2)),centreCirle_d,npoints = 100)
  
  ## create corner flag radius ####
  TopLeftCorner <- circleFun(c(xmin,ymax),200,npoints = 1000)
  TopRightCorner <- circleFun(c(xmax,ymax),200,npoints = 1000)
  BottomLeftCorner <- circleFun(c(xmin,ymin),200,npoints = 1000)
  BottomRightCorner <- circleFun(c(xmax,ymin),200,npoints = 1000)
  
  p <- ggplot() + xlim(c(-10,xmax+10)) + ylim(c(-10,ymax+10)) +
  # add the theme 
  theme_blankPitch() +
  # add the base rectangle of the pitch 
  geom_rect(aes(xmin=0, xmax=xmax, ymin=0, ymax=ymax), fill = grass_colour, colour = line_colour) +
  # add the 18 yard box Left
  geom_rect(aes(xmin=0, xmax=TheBoxHeight[1], ymin=TheBoxWidth[1], ymax=TheBoxWidth[2]), fill = grass_colour, colour = line_colour) + 
  # add the 18 yard box Right
  geom_rect(aes(xmin=TheBoxHeight[2], xmax=xmax, ymin=TheBoxWidth[1], ymax=TheBoxWidth[2]), fill = grass_colour, colour = line_colour) +
  # add the six yard box Left
  geom_rect(aes(xmin=0, xmax=box6yardHeight[1], ymin=box6yardWidth[1], ymax=box6yardWidth[2]), fill = grass_colour, colour = line_colour)  +
  # add the six yard box Right
  geom_rect(aes(xmin=box6yardHeight[2], xmax=xmax, ymin=box6yardWidth[1], ymax=box6yardWidth[2]), fill = grass_colour, colour = line_colour)  + 
  # Add half way line 
  geom_segment(aes(x = xmax/2, y = ymin, xend = xmax/2, yend = ymax),colour = line_colour) +
  # add left D 
  geom_path(data=Dleft, aes(x=x,y=y), colour = line_colour) + 
  # add Right D 
  geom_path(data=Dright, aes(x=x,y=y), colour = line_colour) + 
  # add centre circle 
  geom_path(data=center_circle, aes(x=x,y=y), colour = line_colour) + 
  # add penalty spot left 
  geom_point(aes(x = penspot , y = ymax/2), colour = line_colour) + 
  # add penalty spot right
  geom_point(aes(x = (xmax-(penspot)) , y = ymax/2), colour = line_colour) + 
  # add centre spot 
  geom_point(aes(x = (xmax/2) , y = ymax/2), colour = line_colour) +
  # add Corner Flag corners
  geom_path(data=TopLeftCorner, aes(x=x,y=y), colour = line_colour) +
  geom_path(data=TopRightCorner, aes(x=x,y=y), colour = line_colour) +
  geom_path(data=BottomLeftCorner, aes(x=x,y=y), colour = line_colour) +
  geom_path(data=BottomRightCorner, aes(x=x,y=y), colour = line_colour) +
  geom_segment(aes(x = xmin, y = GoalPosts[1], xend = xmin, yend = GoalPosts[2]),colour = goal_colour, size = 1) +
  # add the goal right
  geom_segment(aes(x = xmax, y = GoalPosts[1], xend = xmax, yend = GoalPosts[2]),colour = goal_colour, size = 1)
  
  return(p)
}
```

## Pitch Plot Fix
```{r}
    data <- fpl_shots %>% 
      dplyr::filter( season == "2019/2020" &
                     player %in% c("Mohamed Salah","Harry Kane") &
                      round %in% (1:38) &
                       result %in% c("Goal") &
                       situation %in% c("OpenPlay")
                     ) 

ggplotly(createPitch(10600, 6500, "#000000", "#FFFFFF", "#000000", "#808080") +
  geom_point(data = data, aes( x = (X*10000*1.2) - 1400, y = 6700 - (Y*10000*0.7), col = result, size = xG, text = paste("Situation:", situation, "<br>", "Result:", result,"<br>","Minute:", minute, "<br>","Date:", date, "<br>", "Assist:", player_assisted)) )   +
  coord_flip(xlim = c(5400, 10685),
              ylim = c(0, 7040)) +
  theme(plot.background = element_rect(fill = "black"),
        title = element_text(colour = "white"), legend.position = "none"), tooltip = 'text'
)


```

# Combine player_shots with fpl data
```{r}
understat_shots <- read.csv("player_shots.csv") 
understat_shots$date <- as.Date(understat_shots$date)

fpl_shots <- read.csv("fpl.csv") %>%  mutate(xG_90 = replace_na(xG_90, 0),
         xGChain_90 = replace_na(xG_90, 0),
         xGBuildup_90 = replace_na(xG_90, 0),
         xA_90 = replace_na(xG_90, 0),
         shots_90 = replace_na(shots_90, 0),
         big_chances_created_90 = replace_na(big_chances_created_90, 0),
         round=as.factor(round)
         ) 


fpl_shots <- fpl_shots[,c("first_name", "second_name","round","club","assists.x", "xA.x","npxG.x","npg.x","opponent", "kickoff_time", "position", "minutes","was_home","element","value","key_passes.x")] %>% 
  dplyr::rename(date = kickoff_time,
                xA = xA.x,
                assists = assists.x,
                npxG = npxG.x,
                npg = npg.x,
                key_passes = key_passes.x)

fpl_shots$date <- as.Date(fpl_shots$date)
fpl_shots$player <- paste(fpl_shots$first_name, fpl_shots$second_name, sep=' ') %>% as.factor()
```

## Repairment
```{r}

understat_shots$player <- as.character(understat_shots$player)
fpl_shots$player <- as.character(fpl_shots$player)

for(i in 1:nrow(understat_shots)){
  if(understat_shots$match_id[i]=="9220"){
    understat_shots$date[i]="2018-08-26"
  } 
}

for(i in 1:nrow(understat_shots)){
  if(understat_shots$player[i] == "N&#039;Golo Kanté"){
    understat_shots$player[i]= "N'Golo Kanté"
  } 
  if(understat_shots$player[i] == "Ben Chilwell"){
    understat_shots$player[i]= "Benjamin Chilwell"
  } 
    if(understat_shots$player[i] == "Sokratis"){
    understat_shots$player[i]= "Sokratis Papastathopoulos"
  } 
}

for(i in 1:nrow(fpl_shots)){
  if(fpl_shots$player[i] == "Bernardo Mota silva"){
    fpl_shots$player[i]= "Bernardo Silva"
  } 
  if(fpl_shots$player[i] == "Felipe Anderson Anderson"){
    fpl_shots$player[i]= "Felipe Anderson"
  } 
    if(fpl_shots$player[i] == "Fernando Rosa"){
    fpl_shots$player[i]= "Fernandinho"
    } 
     if(fpl_shots$player[i] == "Heung-Min Son"){
    fpl_shots$player[i]= "Son Heung-Min"
     }  
    if(fpl_shots$player[i] == "Ricardo Domingos Pereira"){
    fpl_shots$player[i]= "Ricardo Pereira"
       }  
    if(fpl_shots$player[i] == "Richarlison Andrade"){
    fpl_shots$player[i]= "Richarlison"
    } 
    if(fpl_shots$player[i] == "Rúben Diogo Neves"){
    fpl_shots$player[i]= "Rúben Neves"
    }   
    if(fpl_shots$player[i] == "Willian Borges"){
    fpl_shots$player[i]= "Willian"
    }    
}

understat_shots$player <- as.factor(understat_shots$player)
fpl_shots$player <- as.factor(fpl_shots$player)
```

## Bind Shots with FPL data
```{r}
fpl_shots <- right_join(understat_shots, fpl_shots, by = c("date", "player")) %>% 
  dplyr::filter(position != "GK") %>% 
  mutate(player = as.factor(player)) %>% 
  mutate(player = droplevels(player))



```

# Bind FPL shots with FPL picture
```{r}
fpl_photo <- read.csv("Data_Input/2018_2019/players_raw.csv") %>% 
  dplyr::select(c(id, photo)) %>% 
  dplyr::rename(element = id)

fpl_shots <- right_join(fpl_photo, fpl_shots, by = c("element"))
fpl_shots$photo <- gsub('.jpg', '.png', fpl_shots$photo )
fpl_shots$photo <- paste0("p", fpl_shots$photo)
glimpse(fpl_shots)
```

## Create shots variable
```{r}
fpl_shots$shots_in_box <- ifelse(fpl_shots$X >= 0.83 & fpl_shots$Y >= 0.18 & fpl_shots$Y <= 0.78, 1, 0)
fpl_shots$shots <- ifelse(is.na(fpl_shots$X) == F, 1, 0)
fpl_shots$goals <- ifelse(fpl_shots$result == "Goal", 1, 0)
fpl_shots$shots_on_target <- ifelse(fpl_shots$result == "Goal" | fpl_shots$result == "SavedShot", 1, 0)
fpl_shots$shots_off_target <- fpl_shots$shots - fpl_shots$shots_on_target

fpl_shots <- fpl_shots %>% 
  mutate(goals=replace_na(goals,0),
         xG = replace_na(xG, 0),
         shots= replace_na(shots, 0),
         shots_on_target= replace_na(shots_on_target, 0),
         shots_off_target= replace_na(shots_off_target, 0),
         shots_in_box = replace_na(shots_in_box, 0)
         ) 
glimpse(fpl_shots)
```


```{r}
fpl_shots <- rbind(fpl_shots_2018_2019,fpl_shots_2019_2020) %>% 
  mutate(season = as.factor(season)) %>% 
  mutate(player = as.factor(player)) %>% 
  mutate(player = droplevels(player)) 

fpl_shots %>% filter(player == "Abdoulaye Doucouré") %>% dplyr::select(round, season)
glimpse(fpl_shots)
write.csv(fpl_shots, "fpl_shots.csv")
fpl_shots <- read.csv("fpl_shots.csv")
```

```{r}
fpl <- rbind(fpl_2018_2019,fpl_2019_2020)
write.csv(fpl, "fpl.csv")
fpl <- read.csv("fpl.csv") 

is.na(fpl)<-sapply(fpl, is.infinite)
fpl[is.na(fpl)]<-0

fpl$position <- ifelse(fpl$position == "GK", "Goalkeeper", ifelse(fpl$position == "CB", "Defender",ifelse(fpl$position == "FB", "Defender", ifelse(fpl$position == "DM", "Midfielder", ifelse(fpl$position == "AM", "Midfielder", ifelse(fpl$position == "ST",  "Forward", NA)))))) %>% as.factor()

fpl$position <- factor(fpl$position, ordered = T, c("Goalkeeper", "Defender", "Midfielder","Forward"))
glimpse(fpl)

fpl <- fpl %>% 
  mutate(round = as.factor(round))

fpl %>% 
  dplyr::filter(player == "Mohamed Salah" & season == "2019/2020" & round == 19)

```


# Testing Data
```{r}
fpl_shots_filter <- fpl_shots %>%
  dplyr::filter(player == c("Mohamed Salah") & round %in% c(7,8,9,10,11)) %>% 
  dplyr::select(c(player, club, position, round,shots, shots_in_box, shots_on_target, xG, goals,minutes))

# Shots Number
shots <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(shots = sum(shots)) %>% 
  ungroup() %>% 
  dplyr::select(shots)

shots_in_box <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(shots_in_box = sum(shots_in_box))%>% 
  ungroup() %>% 
  dplyr::select(shots_in_box)

shots_on_target <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(shots_on_target = sum(shots_on_target)) %>% 
    ungroup() %>% 
  dplyr::select(shots_on_target)

xG <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(xG = sum(xG))%>% 
    ungroup() %>% 
  dplyr::select(xG)

goals<- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(goals = sum(goals)) %>% 
    ungroup() %>% 
  dplyr::select(goals)

minutes <- fpl_shots_filter %>% 
  dplyr::select(c(player, round,minutes))

minutes <- unique(minutes)

minutes <- minutes %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(minutes = sum(minutes)) %>% 
    ungroup() %>% 
  dplyr::select(c(minutes))

fpl_shots_filter <- fpl_shots_filter %>% 
  dplyr::select(c(player, club, position))

fpl_shots_filter <- unique(fpl_shots_filter)
  
fpl_shots_filter <-  cbind(fpl_shots_filter, minutes, shots, shots_in_box, shots_on_target, xG, goals) %>% 
  dplyr::rename("Player" = player,
                "Club" = club,
                "Position" = position,
                "Minutes Played" = minutes,
                "Shots" = shots,
                "Shots in The Box" = shots_in_box,
                "Shots on Target" = shots_on_target,
                "Goals" = goals)

rownames(fpl_shots_filter) <- fpl_shots_filter$Player

fpl_shots_filter <- fpl_shots_filter %>% 
  dplyr::select(- Player)

fpl_shots_filter <- t(fpl_shots_filter) 


```

```{r}
fpl_filter <- fpl %>%
  dplyr::filter(player == c("Mohamed Salah") & round %in% c(7) & season == "2019/2020") %>% 
  dplyr::select(c(player, club, position, opponent))


rownames(fpl_filter) <- fpl_filter$player
fpl_filter <- fpl_filter %>% 
  dplyr::select(- player)
fpl_filter <- t(fpl_filter)
glimpse(fpl_filter)
```

```{r}

fpl_shots_filter <- fpl_shots %>%
  dplyr::filter(player == c("Mohamed Salah","Harry Kane") & round %in% c(7,8,9,10,11)) %>% 
  dplyr::select(c(player, club, position, round,shots, shots_in_box, shots_on_target, xG, goals,minutes))

shots <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position, round) %>% 
  dplyr::summarise(shots = sum(shots)) %>% 
  ungroup() %>% 
  dplyr::select(c(player, round, shots)) %>% 
  mutate(round=as.numeric(round))

shots_on_target <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position, round) %>% 
  dplyr::summarise(shots_on_target = sum(shots_on_target)) %>% 
  ungroup() %>% 
  dplyr::select(c(shots_on_target)) 

fpl_shots_filter <- cbind(shots,shots_on_target) %>% 
  mutate(shots_on_target_ratio = round(shots_on_target/shots,2)) %>% 
  mutate(shots_on_target_ratio = replace_na(shots_on_target_ratio,0))

ggplotly(ggplot(fpl_shots_filter, aes(round, shots_on_target_ratio)) +
    geom_area(aes(color = player,
fill= fct_reorder(player, shots_on_target_ratio, .desc = TRUE)), position = 'identity', alpha = 0.8)  +theme_calc() + scale_colour_calc() + scale_fill_calc()+ theme_tech(theme="X23andme") + 
     scale_x_continuous(breaks=seq(1,38,1)) +
  labs(title = "Average Points per Round by Position",x = "Round", y="Shots on Target Ratio")+ 
  theme(legend.position = "none"))

```

# situation & shots type
```{r}

situation <- fpl_shots %>% 
  spread(situation, shots) %>% 
  mutate(DirectFreekick = replace_na(DirectFreekick,0),
         FromCorner = replace_na(FromCorner,0),
         OpenPlay = replace_na(OpenPlay,0),
         Penalty = replace_na(Penalty,0),
         SetPiece = replace_na(SetPiece,0),
         ) %>% 
  dplyr::select(c(player, round, opponent, date, DirectFreekick, FromCorner,OpenPlay,Penalty, SetPiece ))  %>% 
  dplyr::filter(player == c("Mohamed Salah","Harry Kane") & round %in% c(7,8,9,10,11) & season %in% c("2019/2020")) 

DirectFreekick <- situation %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(DirectFreekick = sum(DirectFreekick)) %>% 
  ungroup() %>% 
  dplyr::select(DirectFreekick)

FromCorner <- situation %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(FromCorner = sum(FromCorner)) %>% 
  ungroup() %>% 
  dplyr::select(FromCorner)

OpenPlay <- situation %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(OpenPlay = sum(OpenPlay)) %>% 
  ungroup() %>% 
  dplyr::select(OpenPlay)

Penalty <- situation %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(Penalty = sum(Penalty)) %>% 
  ungroup() %>% 
  dplyr::select(Penalty)

SetPiece <- situation %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(SetPiece = sum(SetPiece)) %>% 
  ungroup() %>% 
  dplyr::select(SetPiece)

shots_type <- fpl_shots %>% 
  spread(shotType, shots) %>% 
    mutate(Head = replace_na(Head,0),
         LeftFoot = replace_na(LeftFoot,0),
         RightFoot = replace_na(RightFoot,0),
         OtherBodyPart = replace_na(OtherBodyPart,0)
         ) %>% 
    dplyr::select(c(player, round, opponent, date, Head, LeftFoot,RightFoot,OtherBodyPart)) %>% 
  dplyr::filter(player == c("Mohamed Salah","Harry Kane") & round %in% c(7,8,9,10,11)& season %in% c("2019/2020")) 

Head <- shots_type %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(Head = sum(Head)) %>% 
  ungroup() %>% 
  dplyr::select(Head)

LeftFoot <- shots_type %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(LeftFoot = sum(LeftFoot)) %>% 
  ungroup() %>% 
  dplyr::select(LeftFoot)

RightFoot <- shots_type %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(RightFoot = sum(RightFoot)) %>% 
  ungroup() %>% 
  dplyr::select(RightFoot)

OtherBodyPart <- shots_type %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(OtherBodyPart = sum(OtherBodyPart)) %>% 
  ungroup() %>% 
  dplyr::select(OtherBodyPart)

fpl_shots_filter <- fpl_shots %>%
  dplyr::filter(player == c("Mohamed Salah","Harry Kane") & round %in% c(7,8,9,10,11)& season %in% c("2019/2020")) %>% 
  dplyr::select(c(player, club, position, round, opponent, date,shots, shots_in_box, shots_on_target, xG, goals,minutes))

shots <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(shots = sum(shots)) %>% 
  ungroup() %>% 
  dplyr::select(shots)

shots_in_box <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(shots_in_box = sum(shots_in_box))%>% 
  ungroup() %>% 
  dplyr::select(shots_in_box)

shots_on_target <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(shots_on_target = sum(shots_on_target)) %>% 
    ungroup() %>% 
  dplyr::select(shots_on_target)

xG <- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(xG = sum(xG))%>% 
    ungroup() %>% 
  dplyr::select(xG)

goals<- fpl_shots_filter %>% 
  dplyr::group_by(player, club, position) %>% 
  dplyr::summarise(goals = sum(goals)) %>% 
    ungroup() %>% 
  dplyr::select(goals)

minutes <- fpl_shots_filter %>% 
  dplyr::select(c(player, round,minutes))

minutes <- unique(minutes)

minutes <- minutes %>% 
  dplyr::group_by(player) %>% 
  dplyr::summarise(minutes = sum(minutes)) %>% 
    ungroup() %>% 
  dplyr::select(c(minutes))

fpl_shots_filter <- fpl_shots_filter %>% 
  dplyr::select(c(player))

fpl_shots_filter <- unique(fpl_shots_filter)
  
fpl_shots_filter <-  cbind(fpl_shots_filter, minutes, shots, shots_in_box, shots_on_target, xG, goals, DirectFreekick, OpenPlay, SetPiece,Penalty, FromCorner, Head, LeftFoot, RightFoot, OtherBodyPart) %>% 
  mutate("xG90" = round((xG*90/minutes),2),
         "xG" = round(xG,2),
         "Shots90" = round((shots*90/minutes),2),
         "ShotsinTheBox90" = round((shots_in_box*90/minutes),2),
         "ShotsOnTarget90" = round((shots_on_target*90/minutes),2)
  ) %>% 
  dplyr::rename("Player" = player,
                "Total Shots" = shots,
                "Shots in The Box" = shots_in_box,
                "Shots on Target" = shots_on_target,
                "Goals" = goals,
                "Direct Freekick" = DirectFreekick,
                "Open Play" = OpenPlay,
                "Set Piece" = SetPiece,
                "Penalty" = Penalty,
                "Corner" = FromCorner,
                "Head" = Head,
                "Left Foot" = LeftFoot,
                "Right Foot" = RightFoot,
                "Other Body Parts" = OtherBodyPart
                ) %>% 
  dplyr::select(- c(minutes))

fpl_shots_filter <- fpl_shots_filter %>% gather(key = "observation", value="value", -c(1)) %>% 
  mutate(observation = as.factor(observation)) %>% 
  dplyr::filter(value > 0) 


fpl_shots_filter$observation <- factor(fpl_shots_filter$observation, ordered = T, c("Total Shots", "Shots on Target","Shots in The Box", 
                                                                                    "Direct Freekick", "Open Play","Set Piece","Penalty",
                                                                                    "Corner", "Head", "Left Foot", "Right Foot","Other Body Parts",
                                                                                    "Goals",
                                                                                    "xG","xG90", "Shots90", "ShotsinTheBox90", "ShotsOnTarget90"
                                                                                    ))

ggplot(fpl_shots_filter, aes(x = observation, y = ifelse(test = Player == "Harry Kane",  yes = -value, no = value), fill = Player)) +
  geom_bar(stat = "identity") +
  facet_share(~Player, dir = "h", scales = "free", reverse_num = TRUE) +   # note: scales = "free"
  coord_flip() +
  theme_minimal() +
  labs(y = "Count", x = "Age Band", title = " ") +
  scale_fill_manual(values = c("pink", "blue"))



ggplotly(ggplot(fpl_shots_filter, 
       mapping = aes(x = observation, y = ifelse(test = Player == "Harry Kane",  yes = -value, no = value), 
                     fill = Player)) +
    geom_col() +
    coord_flip() +
    scale_y_continuous(labels = abs, limits = max(fpl_shots_filter$value) * c(-1,1)) +
    labs(y = "Population"))

ggplotly(ggplot(fpl_shots_filter, 
   mapping = aes(
      x = forcats::fct_relabel(observation,
                                    stringr::str_wrap,
                                    width = 10), 
      y = ifelse(test = Player == "Harry Kane",  yes = -value, no = value), 
      fill = Player,
      label= value
   )) +
geom_bar(stat = "identity") +
geom_text(hjust=ifelse(test = fpl_shots_filter$Player == "Harry Kane",  yes = 1.1, no = -0.1), size=3, colour="#505050") +

scale_y_continuous(labels = abs, limits = max(fpl_shots_filter$value) * c(-1,1) * 1.1) +

scale_fill_manual(values=as.vector(c("#d23f67","#505050"))) +

labs(
  x = "",
  y = "",
  fill=""
  
) +
theme_minimal( base_size=20) +   
coord_flip() +
theme( 
  panel.grid.major = element_blank(), 
  panel.grid.minor = element_blank(),
  axis.text.y=element_text(size=12),
  strip.text.x=element_text( size=12),
  legend.position="bottom",
  legend.text=element_text(size=12)
))

ggplotly(tes)
```

# alternative pyramid chart
```{r}
ggplot(fpl_shots_filter, aes(x = observation, y = ifelse(test = Player == "Harry Kane",  yes = -value, no = value), fill = Player, label = value)) +
  geom_bar(stat = "identity") +
  ggpol::facet_share(~Player, dir = "h", scales = "free", reverse_num = TRUE) +   
  coord_flip() +
geom_text(hjust=ifelse(test = fpl_shots_filter$Player == "Harry Kane",  yes = 1.1, no = -0.1), size=3, colour="#505050")+
  theme_minimal() + ggtech::scale_fill_tech(theme = "airbnb") +
geom_text(hjust=ifelse(test = fpl_shots_filter$Player == "Harry Kane",  yes = 1.1, no = -0.1), size=3, colour="white")+
  labs(y = "Count", x = "Age Band", title = " ") 

 ggplot(fpl_shots_filter, aes(x = observation, y = ifelse(test = Player == input$PickPlayer1Shots,  yes = -value, no = value), fill = Player, label = value)) +
     geom_bar(stat = "identity") +
     ggpol::facet_share(~Player, dir = "h", scales = "free", reverse_num = TRUE) +   
     coord_flip() +
     theme_minimal() + ggtech::scale_fill_tech(theme = "airbnb") +
     geom_text(hjust=ifelse(test = fpl_shots_filter$Player == input$PickPlayer1Shots,  yes = 1.1, no = -0.1), size=3, colour="white")+
     labs(y = NULL, x = NULL) +mytheme +
       theme(legend.position = "none",
             plot.background = element_rect(fill = "#2D3741", color = "#2D3741", size = 0),
             panel.background = element_blank(),
             axis.text.y=element_text(size=12),
             strip.text.x=element_text( size=12),
             legend.text=element_text(size=12))

```



```{r}
library (highcharter)

tes <- fpl %>% 
  filter(season == "2019/2020" & round == 18 & player == "Kevin De Bruyne") %>% 
  dplyr::select(team_form, opponent_form, fpl_form, goals_90, xG_90 ,xGChain_90,xGBuildup_90, assists_90, xA_90, shots_90, key_passes_90)

 tes <- unique(tes)
 
 tes <- gather(tes, key = "key", value = "value")
 
 
 tes2 <- fpl %>% 
  filter(season == "2019/2020" & round == 18 & player == "Mohamed Salah" ) %>% 
  dplyr::select(team_form, opponent_form, fpl_form, goals_90, xG_90 ,xGChain_90,xGBuildup_90, assists_90, xA_90, shots_90, key_passes_90)
 
  tes2 <- unique(tes2)
 
 tes2 <- gather(tes2, key = "key", value = "value")
 
 
highchart() %>% 
  hc_chart(polar = TRUE,parallelCoordinates = T, backgroundColor = '#2D3741', parallelAxes = list(gridLineWidth = 2)
           ) %>% 
  hc_title(text = "Budget vs Spending") %>% 
  hc_xAxis(categories = tes$key, 
           tickmarkPlacement = "on",
           lineWidth = 0, gridLineColor = "#FFFF", labels = list(style = list(color = "#FFFF")),   title = list(style = list(color = "#FFFF")), 
        lineColor= "#FFFF",
        minorGridLineColor= "#FFFF",
        tickColor= "#FFFF",
        tickWidth= 1) %>% 
  hc_yAxis(gridLineColor = "transparent", labels = list(enabled = FALSE), 
        lineColor= "transparent",
        gridLineColor= "transparent",
        tickColor= "transparent",
        tickWidth= 0, visible = F,gridLineWidth = 0, lineColor = 'transparent', text = NULL,
       tickLength = 0, ticks = list(display = FALSE), lineWidt = 0,minorTickLength = 0,
   tickLength = 0,
  minorGridLineWidth = 0) %>% 
 hc_series(list(data = tes[,"value"],
            name = "Harry Kane",
      type = "polygon",colors = 'rgba(255,90,95,0.5)', opacity = 10),
      list(data = tes2[,"value"],
            name = "Raheem Sterling",
      type = "polygon", colors = "rgba(255,180,0,0.5)", opacity = 10),
      list(data = tes[,"value"],
            name = "Harry Kane",
      type = "line",colors = 'rgba(255,90,95,1)', opacity = 10),
      list(data = tes2[,"value"],
            name = "Raheem Sterling",
      type = "line",colors = "rgba(255,180,0,1)", opacity = 10)
      
      ) %>% 
  hc_colors(c('rgba(255,90,95,0.5)', "rgba(255,180,0,0.5)")) %>% 
  hc_tooltip(
    borderWidth = 0,
    backgroundColor = 'rgba(0, 0, 0, 0.85)',
    style = list(
      fontSize = '12px', color = "#FFFF"
    )
  ) %>% 
  hc_legend(showInLegend = F) 


```



```{r}
library(highcharter)
sun <- fpl %>% dplyr::filter(round == 19 & season == "2019/2020") %>% 
  group_by(player, club) %>%  
  dplyr::select(team_form, opponent_form, fpl_form, goals_90, xG_90, xGChain_90, xGBuildup_90, assists_90, xA_90, shots_90, key_passes_90) %>%   
  arrange(- fpl_form) %>% 
  dplyr::select(player,club, fpl_form, team_form, opponent_form) %>% 
  head(10)

highchart() %>% 
  hc_colors(c('rgba(255,90,95,0.5)', "rgba(255,180,0,0.5)", "rgba(255,73,2,0.5)")) %>% 
hc_chart(type="column", polar = TRUE, inverted = TRUE, marginTop= 25) %>%
  hc_tooltip(outside = TRUE) %>% 
  hc_pane(size = "85%",
          startAngle = 45,
          endAngle = 270) %>% 
    hc_xAxis(categories = sun$player,
    tickInterval = 1,
    labels = list(
      align = 'right',
      useHTML= T,
      allowOverlap = TRUE,
      step = 1,
      y = 4),
      style = list(
        fontSize = '12px'),
      lineWidth = 0
      ) %>% 
  hc_yAxis(lineWidth = 0,
    reversedStacks = FALSE,
    endOnTick = TRUE,
    showLastLabel = TRUE) %>%
  hc_plotOptions(column = list(
      stacking = 'normal',
      borderWidth = 0,
      pointPadding = 0,
      groupPadding = 0.15,
      pointPlacement = "between",
      dataLabels = list(enabled =T, allowOverlap = T))) %>% 
   hc_series(list(data = sun$fpl_form,
            name = "FPL Form",colors = 'rgba(255,215,0,0.9)'),
      list(data = sun$team_form,
            name = "Team Form"),
      list(data = sun$opponent_form,
            name = "Opponent Form")
      ) 

```

```{r}

fpl_bar <- fpl %>% 
    dplyr::select(player,club, round, season, position, fpl_form, team_form, opponent_form,goals, goals_90, xG_90, xGChain_90, xGBuildup_90, assists_90, xA_90, shots_90, key_passes_90)

names(fpl_bar[,5:16])

sun <- fpl_bar %>% 
  dplyr::filter(round %in% c(19) & season == "2019/2020") %>% 
  dplyr::arrange(- xA_90) %>% 
  head(10) 


%>% 
  dplyr::rename(
    "FPL Form" = "fpl_form",
    "Team Form" = "team_form",
    "Opponent Form" = "opponent_form",
    "Goal90"= "goals_90",
    "xG90" = "xG_90",
    "xA90" = "xA_90",
    "xGChain90" = "xGChain_90",
    "xGBuildup90" = "xGBuildup_90",
    "Assists90" = "assists_90",
    "Shots90" = "shots_90",
    "KP90" = "key_passes_90"
  )

highchart() %>% 
hc_chart(type = 'bar', backgroundColor = '#2D3741') %>%
  hc_tooltip(outside = TRUE, borderWidth = 0,
    backgroundColor = 'rgba(0, 0, 0, 0.85)',
    style = list(
      fontSize = '12px', color = "#FFFF"
    )) %>% 
    hc_xAxis(categories = sun$player, labels = list(style = list(color = "#FFFF"))
      ) %>% 
  hc_yAxis(min = 0, labels = list(style = list(color = "#FFFF"))) %>%
  hc_legend(reversed = T, itemStyle = list(color = "#FFFF")) %>% 
  hc_plotOptions(series = list(
      stacking = 'normal')) %>%
   hc_series(list(data = sun$fpl_form,
            name = "FPL Form",colors = 'rgba(255,215,0,0.9)'),
      list(data = sun$xA_90,
            name = "xA_90"),
      list(data = sun$assists_90,
            name = "assists_90"),    
      list(data = sun$goals_90,
            name = "Goals90"),
      list(data = sun$xG_90,
           name = "xG90")
      
      )  %>% 
  hc_colors(c('rgba(255,90,95,1)', "rgba(255,180,0,1)", "rgba(200,73,2,1)"))

list_sort <- c("FPL Form","Team Form", "Opponent Form","Goal90","xG90","xA90","xGChain90","xGBuildup90", "Assists90","Shots90","KP90")

colnames(is.numeric(sun))
```


```{r}
sun <- fpl %>% dplyr::filter(round == 16 & season == "2019/2020") %>% 
  group_by(club, opponent) %>%  
  dplyr::select(team_form, opponent_form) %>%  
  dplyr::arrange(- team_form, opponent_form) %>% 
  dplyr::select(club, team_form, opponent_form) %>% 
  unique() %>% 
  head(10)


highchart() %>% 
hc_chart(type = 'bar', backgroundColor = '#2D3741') %>%
  hc_tooltip(outside = TRUE, borderWidth = 0,
    backgroundColor = 'rgba(0, 0, 0, 0.85)',
    style = list(
      fontSize = '12px', color = "#FFFF"
    )) %>% 
    hc_xAxis(categories = sun$club, labels = list(style = list(color = "#FFFF")),
             useHTML = T) %>% 
  hc_yAxis(min = 0, labels = list(style = list(color = "#FFFF"))) %>%
  hc_legend(reversed = T, itemStyle = list(color = "#FFFF")) %>% 
  hc_plotOptions(bar = list(dataLabels = list(enabled = T, color = "#FFFF"))) %>%
   hc_series(list(data = sun$team_form,
            name = "Team Form",colors = 'rgba(255,215,0,0.9)'),
            list(data = sun$opponent_form,
            name = "Opponent Form",colors = 'rgba(255,215,0,0.9)')
      
      )  %>% 
  hc_colors(c('rgba(255,90,95,1)', "rgba(255,180,0,1)", "rgba(200,73,2,1)"))
```

```{r}
sun <- fpl %>% dplyr::filter(round == 19 & season == "2019/2020") %>% 
  group_by(club, opponent) %>%  
  dplyr::select(team_form, opponent_form) %>%  
  dplyr::arrange(team_form, -opponent_form) %>% 
  dplyr::select(club, team_form, opponent_form) %>% 
  unique() %>% 
  head(10)


highchart() %>% 
hc_chart(type = 'bar', backgroundColor = '#2D3741') %>%
  hc_tooltip(outside = TRUE, borderWidth = 0,
    backgroundColor = 'rgba(0, 0, 0, 0.85)',
    style = list(
      fontSize = '12px', color = "#FFFF"
    )) %>% 
    hc_xAxis(categories = sun$club, labels = list(style = list(color = "#FFFF"))
      ) %>% 
  hc_yAxis(min = 0, labels = list(style = list(color = "#FFFF"))) %>%
  hc_legend(reversed = T, itemStyle = list(color = "#FFFF")) %>% 
  hc_plotOptions(bar = list(dataLabels = list(enabled = T, color = "#FFFF"))) %>%
   hc_series(list(data = sun$team_form,
            name = "Team Form",colors = 'rgba(255,215,0,0.9)'),
            list(data = sun$opponent_form,
            name = "Opponent Form",colors = 'rgba(255,215,0,0.9)')
      
      )  %>% 
  hc_colors(c('rgba(255,90,95,1)', "rgba(255,180,0,1)", "rgba(200,73,2,1)"))
```

```{r}
sun <- fpl %>% dplyr::filter(round == 16 & season == "2019/2020") %>% 
  group_by(player, club, opponent) %>%  
  dplyr::select(team_form, opponent_form, fpl_form, goals,goals_90, xG_90, xGChain_90, xGBuildup_90, assists_90, xA_90, shots_90, key_passes_90) %>%  
  dplyr::arrange(- xG_90,- team_form, opponent_form) %>% 
  dplyr::select(player,club, fpl_form, team_form, opponent_form,goals, goals_90, xG_90, xGChain_90, xGBuildup_90, assists_90, xA_90, shots_90, key_passes_90) %>% 
  head(10)

highchart() %>% 
hc_chart() %>% 
hc_series(type = "wordcloud", data = sun$shots_90, name = "shots90")
```

```{r}
library(plotly)

# read in data
df <- read.csv("https://cdn.rawgit.com/plotly/datasets/master/Emissions%20Data.csv", stringsAsFactors = F)

# Show only 2011 values
df <- subset(df, Year == "2011")

# Arrange in increasing order of emissions
df <- df %>% dplyr::arrange(Emission)
df <- df[-(1:50),]

#  Add colors
colors <- RColorBrewer::brewer.pal(length(unique(df$Continent)), "Spectral")
continent <- unique(df$Continent)

df$colors <- df$Continent

for(i in 1:length(continent)){
  idx <- df$colors %in% continent[i]   
  df$colors[idx] <- colors[i]
}

# Get incremental angle value
n <- nrow(df) + 20
dtheta <- 2*pi / n
theta <- pi / 2

# Initialise
x.coord <- c()
y.coord <- c()
cols <- c()

# This is for the white - circle in the middle
adjust <-  5

# Initialize plot
p <- plot_ly()

for(ctr in 1:nrow(df)){
  
  a <- df$Emission[ctr] + adjust
  
  x1 <- adjust * cos(theta)
  y1 <- adjust * sin(theta)
  
  x2 <- a * cos(theta)
  y2 <- a * sin(theta)
  
  x.coord <- c(x.coord, x1, x2, NA)
  y.coord <- c(y.coord, y1, y2, NA)
  cols <- c(cols, df$Continent[ctr], df$Continent[ctr], NA)
  
  theta <- theta + dtheta
  
  p <- add_trace(p, 
                 x = c(x1, x2),
                 y = c(y1, y2),
                 mode = "lines", 
                 line = list(width = 5, color = df$colors[ctr]),
                 evaluate = T)
}

# Keep x and y axis extents the same
up <- max(na.omit(c(x.coord, y.coord))) + 10
down <- min(na.omit(c(y.coord, y.coord))) - 10

# Add layout options, shapes etc
p <- layout(p,
            showlegend = F,
            xaxis = list(range = c(down, up), domain = c(0, 0.5),
                         title = "", showgrid = F, zeroline = F, showticklabels = F),
            yaxis = list(range = c(down, up), 
                         title = "", showgrid = F, zeroline = F, showticklabels = F),
            shapes = list(
              list(type = "circle",
                   x0 = (-5 - adjust),
                   y0 = (-5 - adjust),
                   x1 = (5 + adjust),
                   y1 = (5 + adjust),
                   fillcolor = "transparent",
                   line = list(color = "white", width = 2)),
              
              list(type = "circle",
                   x0 = (-15 - adjust),
                   y0 = (-15 - adjust),
                   x1 = (15 + adjust),
                   y1 = (15 + adjust),
                   fillcolor = "transparent",
                   line = list(color = "white", width = 2)),
              
              list(type = "circle",
                   x0 = (-25 - adjust),
                   y0 = (-25 - adjust),
                   x1 = (25 + adjust),
                   y1 = (25 + adjust),
                   fillcolor = "transparent",
                   line = list(color = "white", width = 2)),
              
              list(type = "circle",
                   x0 = (-35 - adjust),
                   y0 = (-35 - adjust),
                   x1 = (35 + adjust),
                   y1 = (35 + adjust),
                   fillcolor = "transparent",
                   line = list(color = "white", width = 2))))


# Add annotations for country names
p <- plotly_build(p)

theta <- pi / 2
textangle <- 90

for(ctr in 1:nrow(df)){

  a <- df$Emission[ctr] + adjust
  a <- a + a/12

  x <- a * cos(theta)
  y <- a * sin(theta)
  
  if(ctr < 51) {xanchor <- "right"; yanchor <- "bottom"}
  if(ctr > 51 & ctr < 84) {xanchor <- "right"; yanchor <- "top"}
  if(ctr > 84) {xanchor <- "left"; yanchor <- "top"}

  p$layout$annotations[[ctr]] <- list(x = x, y = y, showarrow = F,
                             text = paste0(df$Country[ctr]),
                             textangle = textangle,
                             xanchor = xanchor,
                             yanchor = yanchor,
                             font = list(family = "serif", size = 9),
                             borderpad = 0,
                             borderwidth = 0)
  theta <- theta + dtheta
  textangle <- textangle - (180 / pi * dtheta)
  
  if(textangle < -90) textangle <- 90
}

# Titles and some other details
p$layout$annotations[[148]] <- list(xref = "paper", yref = "paper",
                                    x = 0, y = 1, showarrow = F,
                                    xanxhor = "left", yanchor = "top",
                                    align = "left",
                                    text = "Carbon dioxide emissions
(metric tons per capita)",
                                    font = list(size = 25, color = "black"))

p$layout$annotations[[149]] <- list(xref = "paper", yref = "paper",
                                    x = 0, y = 0.9, showarrow = F,
                                    xanxhor = "left", yanchor = "top",
                                    align = "left",
                                    text = "Emissions from burning of solid, liquid and 
gas fuels and the manufacture of cement.",
                                    font = list(size = 18, color = "#808080"))

p$layout$annotations[[150]] <- list(xref = "paper", yref = "paper",
                                    x = 0.15, y = 0.5, showarrow = F,
                                    xanxhor = "left", yanchor = "top",
                                    align = "left",
                                    text = "Annual CO2 emissions
for 147 countries.",
                                    font = list(size = 13, color = "black"))

p$data[[149]] <- list(x = rep(-7, 6), y = c(-6, -4, -2, 0, 2, 4), mode = "markers",
                      marker = list(color = colors, size = 10))

p$data[[150]] <- list(x = rep(1, 6), y = c(-6, -4, -2, 0, 2, 4), mode = "text",
                      text = rev(continent),
                      marker = list(color = colors, size = 10))
p
```

