---
title: "machine learning"
author: "Dhaneswara Mandrasa T."
date: "1/3/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(plotly)
library(data.table)
library(GGally)
library(tidymodels)
library(car)
library(scales)
library(lmtest)
library(dplyr)
library(MASS)
library(plyr)
library(readr)
library(TTR)
library(lubridate)
library(understatr)
library(e1071)
library(partykit)
options(scipen = 100, max.print = 1e+06)
```


```{r}

fpl_ml <- read.csv("fpl.csv")

x <- ts(fpl$minutes , frequency = 1)

y <- matrix(SMA(x,4))*4/360


fpl_ml <- fpl_ml %>% 
  mutate(new_col = y[,1],
         minutes_chance= lag(new_col))

fpl_ml <- fpl_ml %>% 
  mutate(round = as.numeric(round)) %>% 
  dplyr::filter(round >= 5) %>% 
   mutate(round = as.factor(round)) %>% 
  dplyr::select(- c(X, new_col)) %>% 
  mutate_if(is.numeric, round, 3)

glimpse(fpl_ml)

write.csv(fpl_ml, "fpl_ml.csv")
```

# Inspect NA
```{r}
colSums(is.na(fpl_ml))

fpl_ml[is.na(fpl_ml$player) == T,]
```

# Cross Validation
```{r}
set.seed(100)
splitted <- rsample::initial_split(fpl_ml, 0.7, "total_points")
fpl_train <- rsample::training(splitted)
fpl_test <- rsample::testing(splitted)
```

```{r}
fpl_train <- fpl_train %>% 
  dplyr::select(- c(player, round, goals, assists, minutes, date_hour, season))

fpl_test <- fpl_test %>% 
  dplyr::select(- c(player, round, goals, assists, minutes, date_hour, season))
```

```{r}
fpl_train %>% 
  pull(total_points) %>% 
  table() %>% 
  prop.table()
```

```{r}
set.seed(417)
ctrl <- trainControl(method="cv", number=5, repeats = 3)
```

```{r}
fpl_forest <- train(total_points~., fpl_train, method="rf", trControl= ctrl)
```

